### PR TITLE
Fix oidc for safari

### LINKED ISSUE #1395: Make sure OpenID security scheme auth flow works in safari browser

### PR DESCRIPTION
**Pull request by vigoo**
Fixes #1395

### CODE REVIEW

File: golem-worker-service/src/custom_api/oidc/handler.rs [hunk 1]
```diff
@@ -120,10 +120,12 @@ impl OidcHandler {
             .store_authenticated_session(&session_id, session)
             .await?;
 
+        let is_https = scheme.redirect_url.starts_with("https://");
```
Comment (noise64) [inline golem-worker-service/src/custom_api/oidc/handler.rs]: i think this should use `scheme.redirect_url.url().scheme() == "https"` to avoid tricky cases altogether
