### PR TITLE
Initial implementation of recovering from snapshots

### LINKED ISSUE #2423: Implement recovery from saved snapshots
Recovery will work very similarly to how manual update works. We locate the latest Snapshot oplog entry and read the payload. Then call the load-snapshot function, and replay the remaining of the oplog.

If `load-snapshot` fails, we try recovering from the beginning with no snapshots. If that fails too, the agent goes into permanent failed state.

Part of this is adding some new worker executor tests verifying the snapshotting behavior.

### PR DESCRIPTION
**Pull request by vigoo**
Follow-up step for https://github.com/golemcloud/golem/pull/2752

Do not merge yet

Resolves #2423

### CODE REVIEW

File: golem-worker-executor/src/durable_host/mod.rs [hunk 1]
```diff
@@ -2749,7 +2951,21 @@ impl PrivateDurableWorkerState {
...
+            let snapshot_skip =
+                DeletedRegionsBuilder::from_regions(vec![OplogRegion::from_index_range(
+                    OplogIndex::INITIAL.next()..=snapshot_idx,
+                )])
+                .build();
+            regions.set_override(snapshot_skip);
+            regions
+        } else {
+            deleted_regions
+        };
```
Comment (noise64) [inline golem-worker-executor/src/durable_host/mod.rs:2967]: just to check if i understand correctly: after a snapshot, everything before it accounted as deleted?

Comment (vigoo) [reply golem-worker-executor/src/durable_host/mod.rs:2967]: This is the same mechanism that is used for snapshot-based updates to skip the oplog's beginning, so recovery continues from the snapshotting point and ignores what happened before. It's just an override so it is not persisted to the oplog as an actual deleted region.
