### PR TITLE
Fix enum support in moonbit wrapper

### LINKED ISSUE #2096: Moonbit generation fails when there is a type that is union of only literal strings
* The extraction of types succeeds however, moon-bit side fails for `type UnionWithOnlyLiterals = "foo" | "bar" | "baz"`.
* This particular bug was discovered when I developed an agent that has all of the types that the SDK supports. In fact, all other types worked with moonbit generation.

Here is the agent code

```ts
// main.ts

import {BaseAgent, agent} from '@golemcloud/golem-ts-sdk';

import {UnionWithOnlyLiterals} from './model';


@agent()
class FooAgent extends BaseAgent {
    constructor(readonly input: string) {
        super();
        this.input = input;
    }
    
    async myFun(param: UnionWithOnlyLiterals): Promise<UnionWithOnlyLiterals> {
        return param;
    }
}
```

```ts
// model.ts


// The type that doesn't work
export type UnionWithOnlyLiterals = "foo" | "bar" | "baz";

// A type that's working - as an example that proves other types in this file is working
export type TaggedUnion = {tag: 'a', val: string} | {tag: 'b' , val: string};

```

The log for `golem app build` says this (see the last line)

```rust

✔ Metadata saved successfully in .metadata/generated-types.ts!
    Executing external command 'npx --no rollup -- -c' in directory /Users/afsalthaj/projects/my-agent-app/components-ts/my-agent

virtual:agent-main → ../../golem-temp/ts-dist/my-agent/main.js...
created ../../golem-temp/ts-dist/my-agent/main.js in 299ms
    Injecting JS module /Users/afsalthaj/projects/my-agent-app/components-ts/my-agent/../../golem-temp/ts-dist/my-agent/main.js into QuickJS WASM /Users/afsalthaj/
         projects/my-agent-app/components-ts/my-agent/../../wasm/golem_agent.wasm
    Generating agent wrapper for my:agent
      Extracting agent types from /Users/afsalthaj/projects/my-agent-app/components-ts/my-agent/../../golem-temp/agents/my_agent.dynamic.wasm
      Generating agent WIT interface for my:agent
      Generating agent WIT interface implementation to /Users/afsalthaj/projects/my-agent-app/components-ts/my-agent/../../golem-temp/agents/my_agent.wrapper.wasm
/var/folders/7s/5bhhn5gn1q53ky6hsdcwsh6w0000gn/T/.tmpP4ojiL/interface/golem/rpc/types/top.mbt:577:55-577:69 [E2000] Warning (Alert deprecated): Use `Int::unsafe_to_char` instead, and use `Int::to_char` for safe conversion
/var/folders/7s/5bhhn5gn1q53ky6hsdcwsh6w0000gn/T/.tmpP4ojiL/interface/golem/rpc/types/top.mbt:1995:67-1995:81 [E2000] Warning (Alert deprecated): Use `Int::unsafe_to_char` instead, and use `Int::to_char` for safe conversion
/var/folders/7s/5bhhn5gn1q53ky6hsdcwsh6w0000gn/T/.tmpP4ojiL/interface/golem/rpc/types/top.mbt:2789:43-2789:57 [E2000] Warning (Alert deprecated): Use `Int::unsafe_to_char` instead, and use `Int::to_char` for safe conversion
/var/folders/7s/5bhhn5gn1q53ky6hsdcwsh6w0000gn/T/.tmpP4ojiL/interface/golem/agent/common/top.mbt:48:50-48:61 [E0035] Warning: The word `constructor` is reserved for possible future use. Please consider using another name.
/var/folders/7s/5bhhn5gn1q53ky6hsdcwsh6w0000gn/T/.tmpP4ojiL/interface/golem/agent/common/top.mbt:52:49-52:60 [E0035] Warning: The word `constructor` is reserved for possible future use. Please consider using another name.
/var/folders/7s/5bhhn5gn1q53ky6hsdcwsh6w0000gn/T/.tmpP4ojiL/interface/golem/agent/guest/top.mbt:897:74-897:88 [E2000] Warning (Alert deprecated): Use `Int::unsafe_to_char` instead, and use `Int::to_char` for safe conversion
/var/folders/7s/5bhhn5gn1q53ky6hsdcwsh6w0000gn/T/.tmpP4ojiL/interface/golem/agent/guest/top.mbt:2011:92-2011:106 [E2000] Warning (Alert deprecated): Use `Int::unsafe_to_char` instead, and use `Int::to_char` for safe conversion
/var/folders/7s/5bhhn5gn1q53ky6hsdcwsh6w0000gn/T/.tmpP4ojiL/interface/golem/agent/guest/top.mbt:2270:92-2270:106 [E2000] Warning (Alert deprecated): Use `Int::unsafe_to_char` instead, and use `Int::to_char` for safe conversion
/var/folders/7s/5bhhn5gn1q53ky6hsdcwsh6w0000gn/T/.tmpP4ojiL/interface/golem/agent/guest/top.mbt:2552:74-2552:88 [E2000] Warning (Alert deprecated): Use `Int::unsafe_to_char` instead, and use `Int::to_char` for safe conversion
/var/folders/7s/5bhhn5gn1q53ky6hsdcwsh6w0000gn/T/.tmpP4ojiL/gen/interface/my/agent/fooAgent/stub.mbt:37:3-37:24 [E4024] The type/trait UnionWithOnlyLiterals is not found.

```

### PR DESCRIPTION
**Pull request by vigoo**
Resolves #2096

### CODE REVIEW

File: cli/golem-cli/src/model/agent/test.rs [hunk 1]
```diff
@@ -368,3 +368,47 @@ pub fn reproducer_for_multiple_types_called_element() -> Vec<AgentType> {
         },
     ]
 }
+
+pub fn reproducer_for_issue_with_enums() -> Vec<AgentType> {
```
Comment (afsalthaj) [inline cli/golem-cli/src/model/agent/test.rs:372]: Now this could be renamed to something else?

File: cli/golem-cli/src/model/agent/wit.rs [hunk 2]
```diff
@@ -1250,6 +1250,46 @@ mod tests {
...
 
+    #[test]
+    pub fn enum_type() {
+        let component_name = "test:agent".into();
+        let agent_types = reproducer_for_issue_with_enums();
+
+        let wit = super::generate_agent_wrapper_wit(&component_name, &agent_types)
+            .unwrap()
+            .single_file_wrapper_wit_source;
+        // println!("{wit}");
```
Comment (afsalthaj) [inline cli/golem-cli/src/model/agent/wit.rs:1261]: and may be remove this comment too.
