### PR TITLE
TS REPL: CLI commands, eval

### LINKED ISSUE #2418: Add built-in functions to work with Golem
Come up with an initial set of functions makes working in the REPL with Golem nicer - these could be discovery related (find metadata, type information, etc of agents etc), state observation (list agents, get metadata, get oplog) and control (interrupt/delete agents etc).

### LINKED ISSUE #2690: CLI: Add final success / failure messages to build, deploy (plan)
So it is easier to match on those in REPL (or for agents) for basic command integrations.

### LINKED ISSUE #2691: TS REPL: Show agent type info (on start and by repl command)

### LINKED ISSUE #2692: TS REPL: Restore eval script support

### LINKED ISSUE #2695: TS REPL: module completion bug on dot only
`simpleAgentClient.` is not working (but `simpleAgentClient.S`  works)

### LINKED ISSUE #2709: Improve error reporting when substituting env vars into the manifest

### PR DESCRIPTION
**Pull request by noise64**
### Changes
- resolves #2418
- resolves #2690
- resolves #2691
- resolves #2692
- resolves #2695
- resolves #2709
- adds new dev-release profile for local CLI testing
- adds argument placeholder completion

### Agent type info on REPL startup
image

### Auto-wired (filtered set of) CLI commands as REPL builtin command
image

### Completions for the wrapped CLI commands
image

### Argument placeholder completions
image

### Script mode with separated type info on stderr, and "auto-jsonified" output with default REPL output fallback on stdout
image

### Example of summary messages
image

### CODE REVIEW

**Comment by vigoo** [comment]
Question / consideration for a future PR: do we want to show the `RemoteMethod` type in the REPL? It is the truth but it's our type and probably just showing the simple case (the blocking invoke function type) is more understandable?

File: cli/golem-cli/src/command_handler/repl/mod.rs [hunk 1]
```diff
@@ -155,26 +161,56 @@ impl ReplHandler {
             }
             let repl_history_file_path = fs::canonicalize_path(&repl_history_file_path)?;
 
+            let repl_cli_commands_metadata_json_path = app_ctx
+                .application()
+                .repl_cli_commands_metadata_json(language);
+            // TODO: cleanup
```
Comment (vigoo) [inline cli/golem-cli/src/command_handler/repl/mod.rs:167]: What needs to be cleaned up, and do we have a ticket that covers it?

File: cli/golem-cli/src/command_handler/repl/typescript.rs [hunk 2]
```diff
@@ -251,15 +274,22 @@ impl TypeScriptRepl {
...
+                  appMainDir: {app_main_dir},
                   agents: {{
                   {agents_config}
                   }},
                   historyFile: {repl_history_file_path},
+                  cliCommandsMetadataJsonPath: {repl_cli_commands_metadata_json_path},
                 }});
 
-                await repl.run();
+                void repl.run();
```
Comment (vigoo) [inline cli/golem-cli/src/command_handler/repl/typescript.rs:286]: Learning something new about JS every day :)
