### PR TITLE
Fix issues in `into-value`  and `from-value-and-type` derivations 

### LINKED ISSUE #2380: Fix  `IntoValue` and `FromValueAndType` derivation for enum with variants
```rs

#[derive(IntoValue, FromValueAndType)]
enum MyEnum {
    Complex { inner: String, count: u32 },
    Simple(u32),
}

There are multiple issues, both at compile time and runtime.

### PR DESCRIPTION
**Pull request by afsalthaj**
Fix #2380

I can paste the pre- and -post expansion later (but see mainly add-to-type builder)

Added tests for macro derivations within `golem_rust` crate as it is possible with the changes done [here](https://github.com/golemcloud/golem/pull/2352) with proc-macros-crate.

I have added explicitly into-value and from-value separate tests, along with a round trip tests for easier debugging, and if possible, let's keep those explicit non-round-trip tests too - for future reference/debugging.

# Issues fixed

## Issue 1

```
#[derive(IntoValue)]
enum MyEnum {
   Simple,
    Complex {
        id: u32,
        name: String,
    },
}

```

failed with compilation error: 

(mainly because of wrong nesting of builder and builder variable name ambiguity or something - anyway fixed)

```
expected one of `.`, `;`, `?`, `}`, or an operator, found `builder`

no rules expected keyword `let`
Note: while trying to match end of macro
proc-macro derive produced unparsable tokens
```

## Issue 2

```rust
#[derive(IntoValue)]
enum MyEnum {
     Complex2(u32, String)
}
```

failed with

```
proc-macro derive panicked
Help: message: called `Option::unwrap()` on a `None` valu

```

### Issue 3 (FromValueAndType derivation)

```rust

#[derive(IntoValue, FromValueAndType)]
enum MyEnum {
    Complex2 {
        hello: String,
        number: i32,
    }

```

```
expected `,`

expected a pattern, found an expression
Note: arbitrary expressions are not allowed in patterns: <https://doc.rust-lang.org/book/ch19-00-patterns.html>
proc-macro derive produced unparsable tokens

unexpected `,` in patter
```

there were multiple reasons for it - details don't matter much. fixed and added tests 

### Issue 4

Fixing the above still resulted in extraction error, that the element is unavailable - which is at runtime..
This is because the logic of extracting the fields was wrong that it always pointed to the outer extractor.. This is fixed.

# Macro expansions (main vs PR)

Expansions for the following code

```rust
#[derive(IntoValue, FromValueAndType)]
enum MyEnum {
    Simple,
    Complex1(u32),
    Complex2(u32, String) // this if included, won't expand in main branch because of above reason
    Complex3 {
        id: u32,
        name: String,
    },
}
```

### IntoValue Main branch

```rust

impl golem_rust::value_and_type::IntoValue for MyEnum {
    fn add_to_builder<B: golem_rust::value_and_type::NodeBuilder>(self, builder: B) -> B::Result {
        match self {
            MyEnum::Simple => { builder.variant_unit(0u32) }
            MyEnum::Complex1(inner) => {
                let builder = builder.variant(1u32);
                inner.add_to_builder(builder).finish()
            }
            MyEnum::Complex3 {
                id, name
            } => {
                let builder = builder.variant(2u32);
                let builder = builder.record();
                vec![let builder = id . add_to_builder (builder . item ()); let builder = name . add_to_builder (builder . item ()); ];
                builder.finish().finish()
            }
        }
    }
    fn add_to_type_builder<B: golem_rust::value_and_type::TypeNodeBuilder>(builder: B) -> B::Result {
        let builder = builder.variant(Some("MyEnum".to_string()), None);
        let builder = builder.unit_case("simple");
        let builder = <u32 as golem_rust::value_and_type::IntoValue>::add_to_type_builder(builder.case("complex1"));
        let builder = builder.case("complex3");
        let builder = builder.record(Some("MyEnum".to_string()), None);
        let builder = <u32 as golem_rust::value_and_type::IntoValue>::add_to_type_builder(builder.field("id"));
        let builder = <String as golem_rust::value_and_type::IntoValue>::add_to_type_builder(builder.field("name"));
        builder.finish()
        builder.finish   ( ) } }
```

###  IntoValue PR branch

```rust

impl golem_rust::value_and_type::IntoValue for MyEnum {
    fn add_to_builder<B: golem_rust::value_and_type::NodeBuilder>(self, builder: B) -> B::Result {
        match self {
            MyEnum::Simple => { builder.variant_unit(0u32) }
            MyEnum::Complex1(inner) => {
                let builder = builder.variant(1u32);
                inner.add_to_builder(builder).finish()
            }
            MyEnum::Complex2(f0, f1) => {
                let builder = builder.variant(2u32);
                let builder = builder.tuple();
                let builder = f0.add_to_builder(builder.item());
                let builder = f1.add_to_builder(builder.item());
                builder.finish().finish()
            }
            MyEnum::Complex3 {
                id, name
            } => {
                let builder = builder.variant(3u32);
                let builder = builder.record();
                let builder = id.add_to_builder(builder.item());
                let builder = name.add_to_builder(builder.item());
                builder.finish().finish()
            }
        }
    }
    fn add_to_type_builder<B: golem_rust::value_and_type::TypeNodeBuilder>(builder: B) -> B::Result {
        let mut builder = builder.variant(Some("MyEnum".to_string()), None);
        builder = builder.unit_case("simple");
        builder = <u32 as golem_rust::value_and_type::IntoValue>::add_to_type_builder(builder.case("complex1"));
        builder = {
            let builder = builder.case("complex2");
            let builder = builder.tuple(Some("MyEnum".to_string()), None);
            let builder = <u32 as golem_rust::value_and_type::IntoValue>::add_to_type_builder(builder.item());
            let builder = <String as golem_rust::value_and_type::IntoValue>::add_to_type_builder(builder.item());
            let builder = builder.finish();
            builder
        };
        builder = {
            let builder = builder.case("complex3");
            let builder = builder.record(Some("MyEnum".to_string()), None);
            let builder = <u32 as golem_rust::value_and_type::IntoValue>::add_to_type_builder(builder.field("id"));
            let builder = <String as golem_rust::value_and_type::IntoValue>::add_to_type_builder(builder.field("name"));
            let builder = builder.finish();
            builder
        };
        builder.finish   ( ) } }
```

### FromValueAndType Main branch

Don't worry about the logic here - the syntax is wrong, and hard for format

```rust 
impl golem_rust::value_and_type::FromValueAndType for MyEnum {
    fn from_extractor<'a, 'b>(extractor: &'a impl golem_rust::value_and_type::WitValueExtractor<'a, 'b>) -> Result<Self, String> {
        let (idx, inner) = extractor.variant().ok_or_else(|| "MyEnum should be variant".to_string())?;
        match idx {
            0u32 => { Ok(MyEnum::Simple) }
            1u32 => { Ok(MyEnum::Complex1(<u32 as golem_rust::value_and_type::FromValueAndType>::from_extractor(&inner.ok_or_else(|| "Missing Complex1 body".to_string())?)?)) }
            Ok(MyEnum::Complex2 { < u32   as   golem_rust   ::   value_and_type   ::   FromValueAndType   >::from_extractor   ( & extractor   .   tuple_element   ( 0usize   ).ok_or_else   ( | | "Missing tuple element #0".to_string   ( ) ) ? ) ?, < String   as   golem_rust   ::   value_and_type   ::   FromValueAndType   >::from_extractor   ( & extractor   .   tuple_element   ( 1usize   ).ok_or_else   ( | | "Missing tuple element #1".to_string   ( ) ) ? ) ? }),
            Ok(MyEnum::Complex3 {
                   id: <u32 as golem_rust::value_and_type::FromValueAndType>::from_extractor   ( & extractor   .   field   ( 0usize   ).ok_or_else   ( | | "Missing id field".to_string   ( ) ) ? ) ?, name: <String as golem_rust::value_and_type::FromValueAndType>::from_extractor   ( & extractor   .   field   ( 1usize   ).ok_or_else   ( | | "Missing name field".to_string   ( ) ) ? ) ?
               }),
            _ => Err(::alloc::__export::must_use({
                ::alloc::fmt::format(format_args!("Invalid MyEnum variant: {idx}", idx = idx))
            })),
        } } }
```

### FromValueAndType PR branch

```rust
impl golem_rust::value_and_type::FromValueAndType for MyEnum {
    fn from_extractor<'a, 'b>(extractor: &'a impl golem_rust::value_and_type::WitValueExtractor<'a, 'b>) -> Result<Self, String> {
        let (idx, inner) = extractor.variant().ok_or_else(|| "MyEnum should be variant".to_string())?;
        match idx {
            0u32 => { Ok(MyEnum::Simple) }
            1u32 => { Ok(MyEnum::Complex1(<i32 as golem_rust::value_and_type::FromValueAndType>::from_extractor(&inner.ok_or_else(|| "Missing Complex1 body".to_string())?)?)) }
            2u32 => {
                let (field_0, field_1) = <(i32, String) as golem_rust::value_and_type::FromValueAndType>::from_extractor(&inner.ok_or_else(|| "Missing tuple element #0".to_string())?)?;
                Ok(MyEnum::Complex2(field_0, field_1))
            }
            3u32 => {
                let inner = &inner.ok_or_else(|| "Missing field".to_string())?;
                Ok(MyEnum::Complex3 { x: <String as golem_rust::value_and_type::FromValueAndType>::from_extractor(&<golem_rust::wasm_rpc::WitNodePointer as golem_rust::value_and_type::WitValueExtractor>::field(&inner, 0usize).ok_or_else(|| "Missing x field".to_string())?)?, y: <bool as golem_rust::value_and_type::FromValueAndType>::from_extractor(&<golem_rust::wasm_rpc::WitNodePointer as golem_rust::value_and_type::WitValueExtractor>::field(&inner, 1usize).ok_or_else(|| "Missing y field".to_string())?)? })
            }
            _ => Err(::alloc::__export::must_use({
                ::alloc::fmt::format(format_args!("Invalid MyEnum variant: {idx}", idx = idx))
            })),
        }
    }
}
```

### CODE REVIEW

File: sdks/rust/golem-rust/src/value_and_type/mod.rs [hunk 1]
```diff
@@ -1157,3 +1157,193 @@ impl FromValueAndType for ResourceMode {
...
+    #[derive(IntoValue, FromValueAndType, PartialEq, Debug, Clone)]
+    enum MyEnum {
+        Simple,
+        Complex1(i32),
+        Complex2(i32, String),
+        Complex3 { x: String, y: bool },
+    }
+
+    #[test]
+    fn test_into_value_derivation_enum() {
```
Comment (afsalthaj) [inline sdks/rust/golem-rust/src/value_and_type/mod.rs:1179]: let's keep these 1 directional tests too (along with the round trip down below), since it talks the exact serialized value, and easier to debug in future
