### PR TITLE
Fixes for oplog and blobstore related issues

### LINKED ISSUE #1501: Benchmark result investigation: explain why local RPC invocations became significantly slower

### PR DESCRIPTION
**Pull request by vigoo**
Fixes [#1501](https://github.com/golemcloud/golem-cloud/issues/1501)

### CODE REVIEW

File: golem-common/src/retriable_error.rs [hunk 1]
```diff
@@ -15,7 +15,15 @@
...
 pub trait IsRetriableError {
+    /// Returns true if the error is retriable.
     fn is_retriable(&self) -> bool;
+
+    /// Returns a loggable string representation of the error. If it returns None, the error
+    /// will not be logged and traced.
+    ///
+    /// This is useful to accept some errors as the expected response (such as a not-found result
+    /// when looking for a resource).
+    fn is_loggable(&self) -> Option<String>;
```
Comment (noise64) [inline golem-common/src/retriable_error.rs:26]: maybe as_loggable?

**Review by noise64 — APPROVED** [review]
