### PR TITLE
Oplog archivation and worker enumeration related fixes and tests

### LINKED ISSUE #983: Investigate worker enumeration with different oplog archive states
There were reports that workers with archived oplogs are not (or not always?) returned by the worker enumeration, but if they are interacted with, leading to new entries written to the primary oplog, they reappear. 

This needs to be investigated / some new tests written, and fixed.

### PR DESCRIPTION
**Pull request by vigoo**
Resolves #983

### CODE REVIEW

**Review by afsalthaj — APPROVED** [review]

**Review by noise64 — APPROVED** [review]

File: golem-worker-executor-base/src/storage/blob/sqlite.rs [hunk 1]
```diff
@@ -154,11 +221,15 @@ impl BlobStorage for SqliteBlobStorage {
         namespace: BlobStorageNamespace,
         path: &Path,
     ) -> Result<(), String> {
+        let path_like = format!("{}%", Self::path_string(path));
+        let query = sqlx::query("DELETE FROM blob_storage WHERE namespace = ?  AND path LIKE ?;")
```
Comment (noise64) [inline golem-worker-executor-base/src/storage/blob/sqlite.rs]: `?   AND` double space

File: golem-worker-executor-base/src/storage/indexed/sqlite.rs [hunk 2]
```diff
@@ -84,11 +113,28 @@ impl IndexedStorage for SqliteIndexedStorage {
         cursor: ScanCursor,
         count: u64,
     ) -> Result<(ScanCursor, Vec<String>), String> {
-        self.pool
+        let key = pattern.replace("*", "%").replace("?", "_");
+        let query =
+            sqlx::query_as("SELECT key FROM index_storage WHERE namespace = ? AND key LIKE ? ORDER BY key LIMIT ? OFFSET ?;")
+                .bind(Self::namespace(namespace))
+                .bind(&key)
+                .bind(sqlx::types::Json(count))
```
Comment (noise64) [inline golem-worker-executor-base/src/storage/indexed/sqlite.rs:121]: why these are json?

**Review by noise64 — APPROVED** [review]
