### PR TITLE
Add test for rust code first routes and fix bugs related to unstructured binary

### LINKED ISSUE #2558: Code First Routes: Implement integration test for agents with code first route
We need to decide on how to implement the integration tests for agents with code first routes

Given typescript SDK and backend is implemented by this time, we should aim to have atleast a full end to end working test with TS.

Later once, Rust is implemented, we should update these tests with Rust agents.

### PR DESCRIPTION
**Pull request by afsalthaj**
Fixes #2558 

A few observations:

https://github.com/golemcloud/golem/issues/2725
https://github.com/golemcloud/golem/issues/2724

And 2 more small issues which I will fix in a PR soon
* endpoint parameter syntax errors should result in compilation errors. I think its not working for headers
* disallow adding endpoints to static functions

### CODE REVIEW

File: integration-tests/tests/custom_api/http_test_context.rs [hunk 1]
```diff
@@ -0,0 +1,191 @@
...
+        client,
+        base_url,
+        user,
+        env_id: env.id,
+        deployment_revision: deployment.revision,
+        host_header,
+    })
+}
+
+pub async fn run_webhook_callback_test(
```
Comment (mschuwalow) [inline integration-tests/tests/custom_api/http_test_context.rs]: Personally, I would not have extracted this one.

Comment (afsalthaj) [reply integration-tests/tests/custom_api/http_test_context.rs]: I had some doubts on it... may be I will revert it back
