### PR TITLE
Fix deployment listing

### LINKED ISSUE #1470: API deployment listing API should behave the same in OSS and Cloud

### PR DESCRIPTION
**Pull request by afsalthaj**
Fix #1470 

Corresponding cloud PR: https://github.com/golemcloud/golem-cloud/pull/1652/files

### CODE REVIEW

File: golem-worker-service-base/src/service/gateway/api_deployment.rs [hunk 1]
```diff
@@ -195,11 +199,17 @@ impl<Namespace: GolemNamespace, AuthCtx: GolemAuthCtx>
...
 
+    // A site is owned by a namespace (i.e, host and subdomain
+    // Only the authorised namespace is allowed to fetch the existing deployments in that site
     async fn fetch_existing_deployments(
         &self,
+        namespace: &Namespace,
         site: &ApiSite,
     ) -> Result<Vec<ApiDeploymentRecord>, ApiDeploymentError<Namespace>> {
-        let deployments = self.deployment_repo.get_by_site(&site.to_string()).await?;
+        let deployments = self
```
Comment (afsalthaj) [inline golem-worker-service-base/src/service/gateway/api_deployment.rs:209]: This will end up in cloud, taking a project-id too to get the existing deployments in a site.
As far the token has access to the project, the deployments can be listed.

File: golem-worker-service-base/src/repo/api_deployment.rs [hunk 2]
```diff
@@ -54,9 +54,17 @@ impl ApiDeploymentRecord {
 
 #[async_trait]
 pub trait ApiDeploymentRepo {
-    async fn create(&self, deployments: Vec<ApiDeploymentRecord>) -> Result<(), RepoError>;
+    async fn create(
+        &self,
+        namespace: &str,
```
Comment (mschuwalow) [inline golem-worker-service-base/src/repo/api_deployment.rs:59]: What is the reason for including the namespace as a separate parameter? Looks like it's already present in the ApiDeploymentRecord

Comment (afsalthaj) [reply golem-worker-service-base/src/repo/api_deployment.rs:59]: to make sure the deployment is only to 1 namespace and its a vector of deployment record that may havve multiple namespaces, ok now it reminds me to do a validation here

**Review by vigoo — APPROVED** [review]
