### PR TITLE
Fix RPC performance regression by better caching

### LINKED ISSUE #3195: Investigate and fix rpc benchmark regression around 10th of April

### PR DESCRIPTION
**Pull request by vigoo**
Resolves #3195 

Fixes RPC performance regression introduced by https://github.com/golemcloud/golem/pull/3112 - keeps all the relevant chanes of the original PR, just adds caching for the latest component metadata now that we have an invalidation broadcast channel we can subscribe to.

### CODE REVIEW

File: golem-worker-executor/src/services/registry_event_subscriber.rs [hunk 1]
```diff
@@ -59,6 +64,9 @@ impl RegistryInvalidationHandler for WorkerExecutorRegistryInvalidationHandler {
                     environment_id = %environment_id,
                     "Received deployment changed event, invalidating environment caches"
                 );
+                self.component_service
+                    .invalidate_latest_deployed_metadata_for_environment(*environment_id)
```
Comment (noise64) [inline golem-worker-executor/src/services/registry_event_subscriber.rs:68]: just a comment in general, we keep adding "latest" naming, when it should be called "current" (given it can go back), for deployments. at least that was the agreed naming originally.

**Review by noise64 — APPROVED** [review]
