### PR TITLE
Fix `get_id` in `Agent` 

### LINKED ISSUE #2275: `getAgentId` doesn't seem to work in Rust code first
[Tests](https://github.com/golemcloud/golem/pull/2259) failed for `getId` function available for all agents. Example: `use golem_rust:agentic:Agent; self.get_id()`

### PR DESCRIPTION
**Pull request by afsalthaj**
Fix #2275 

There was nested borrowing resulted in runtime errors. This fixes it

### CODE REVIEW

**Comment by afsalthaj** [comment]
Merging on to integration test PR

File: cli/golem-cli/tests/app/agents.rs [hunk 1]
```diff
@@ -120,8 +120,7 @@ async fn test_rust_code_first_with_rpc_and_all_types() {
         assert!(outputs.success(), "function {func} failed");
     }
 
-    // TODO; Uncomment after fixing https://github.com/golemcloud/golem/issues/2275
-    // run_and_assert(&ctx, "get-agent-id", &[]).await;
+    run_and_assert(&ctx, "get-agent-id", &[]).await;
```
Comment (afsalthaj) [inline cli/golem-cli/tests/app/agents.rs:123]: Implementation: 

https://github.com/golemcloud/golem/blob/rust_sdk_integration_tests/cli/golem-cli/test-data/rust-code-first-snippets/lib.rs#L93
