### PR TITLE
 Handle invocations while a worker is deleting gracefully 

### LINKED ISSUE #2212: Unwrap error
```
thread 'tokio-runtime-worker' panicked at golem-worker-executor/src/durable_host/replay_state.rs:319:60:
called `Option::unwrap()` on a `None` value
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

not sure how to reproduce (running launch demo agents + interrupt/delete by `deploy --reset`)

### PR DESCRIPTION
**Pull request by mschuwalow**
resolves #2212

### CODE REVIEW

File: golem-worker-executor/src/grpc/mod.rs [hunk 1]
```diff
@@ -822,8 +809,12 @@ impl<Ctx: WorkerCtx, Svcs: HasAll<Ctx> + UsesAllDeps<Ctx = Ctx> + Send + Sync +
     ) -> Result<(), WorkerExecutorError> {
         let full_function_name = request.name();
 
+        tracing::warn!("begin get_or_create worker");
```
Comment (mschuwalow) [inline golem-worker-executor/src/grpc/mod.rs]:
```suggestion
```

File: golem-worker-executor/src/grpc/mod.rs [hunk 2]
```diff
@@ -822,8 +809,12 @@ impl<Ctx: WorkerCtx, Svcs: HasAll<Ctx> + UsesAllDeps<Ctx = Ctx> + Send + Sync +
...
+
         let worker = self.get_or_create(request).await?;
 
+        tracing::warn!("end get_or_create worker");
```
Comment (mschuwalow) [inline golem-worker-executor/src/grpc/mod.rs]:
```suggestion

```

File: golem-worker-executor/src/grpc/mod.rs [hunk 3]
```diff
@@ -836,6 +827,8 @@ impl<Ctx: WorkerCtx, Svcs: HasAll<Ctx> + UsesAllDeps<Ctx = Ctx> + Send + Sync +
             .collect::<Result<Vec<_>, _>>()
             .map_err(|msg| WorkerExecutorError::ValueMismatch { details: msg })?;
 
+        tracing::warn!("begin invoke");
```
Comment (mschuwalow) [inline golem-worker-executor/src/grpc/mod.rs]:
```suggestion

```
