### PR TITLE
Implemented golden test for worker recovery and fixed issues

### LINKED ISSUE #1006: Worker recovery issue after the oplog enumeration changes
```
% golem-cli worker get --component-name cart  --worker-name user003
Got metadata for worker user003

Worker URN:               urn:worker:df93bd28-e341-453f-9dd7-3fc6bec20b23/user003
Component URN:            urn:component:df93bd28-e341-453f-9dd7-3fc6bec20b23
Worker name:              user003
Component version:        0
Created at:               2024-10-09 09:24:31.422 UTC
Component size:           677.22 KiB
Total linear memory size: 4.25 MiB
Environment variables:    PRODUCT_COMPONENT_ID=ef4b7e5f-c2ff-451f-becc-2f20e313ba29;ORDER_COMPONENT_ID=2982f02f-97bc-4539-801c-a5483a9c2d03;PRICING_COMPONENT_ID=6f7a022d-e600-40ec-bb5e-44cb94339d98
Status:                   Failed
Retry count:              4
Last error:
  error while executing at wasm backtrace:
      0: 0x705b9 - wit-component:shim!indirect-wasi:cli/environment@0.2.0-get-environment
      1: 0x6d1a8 - wit-component:adapter:wasi_snapshot_preview1!wasi_snapshot_preview1::State::get_environment::h3dc87564e4fc1678
      2: 0x6d3b2 - wit-component:adapter:wasi_snapshot_preview1!environ_sizes_get
      3: 0x705e1 - wit-component:shim!adapt-wasi_snapshot_preview1-environ_sizes_get
      4: 0x65c44 - product_stub.wasm!__wasi_environ_sizes_get
      5: 0x65ca6 - product_stub.wasm!__wasilibc_initialize_environ
      6: 0x65c7a - product_stub.wasm!__wasilibc_ensure_environ
      7: 0x65d49 - product_stub.wasm!getenv
      8: 0x6190f - product_stub.wasm!std::panic::get_backtrace_style::hd56c3eb4d213759c
      9: 0x621a5 - product_stub.wasm!std::panicking::rust_panic_with_hook::h2ed697044fa66de8
     10: 0x61e6b - product_stub.wasm!std::panicking::begin_panic_handler::{{closure}}::hd3fce676619be24b
     11: 0x61ddc - product_stub.wasm!std::sys::backtrace::__rust_end_short_backtrace::hf4c64ea258ae1491
     12: 0x5e4b8 - product_stub.wasm!rust_begin_unwind
     13: 0x5e43e - product_stub.wasm!core::panicking::panic_fmt::hc988c56e45068cc1
     14: 0x597a5 - product_stub.wasm!core::option::expect_failed::h43b4fb3f3e8dd1e9
     15: 0x5df7c - product_stub.wasm!golem:product-stub/stub-product#[method]api.blocking-get
     16:  0x445 - <unknown>!<wasm function 24>
     17: 0x3350c - wit-component:shim!indirect-golem:product-stub/stub-product-[method]api.blocking-get
     18: 0xe3ba - cart.wasm!golem:cart/api#add-item: Unexpected oplog entry: expected golem_environment::get_environment, got golem_environment::get_arguments
```

### PR DESCRIPTION
**Pull request by vigoo**
Resolves #1006

### CODE REVIEW

File: golem-worker-executor-base/tests/compatibility/v1_1.rs [hunk 1]
```diff
@@ -1,15 +1,81 @@
...
+    let sir3 =
+        SerializableInvokeResult::Completed(Ok(ValueAndType::new(Value::Bool(true), bool())
+            .try_into()
+            .unwrap()));
+    let sir4 = SerializableInvokeResult::Completed(Err(RpcError::Denied {
+        details: "not now".to_string(),
+    }));
+
+    let mut mint = Mint::new("tests/goldenfiles");
+    backward_compatible("serializable_invoke_result_v11_pending", &mut mint, sir1);
```
Comment (afsalthaj) [inline golem-worker-executor-base/tests/compatibility/v1_1.rs:69]: 👍
