### PR TITLE
Write exit and error details to the oplog

### LINKED ISSUE #289: Make Failed and Exited status computable from oplog
Currently we don't store enough information in the oplog to be able to restore the `Failed` (after N retries) and `Exited` (when the error was the special exit signal) statuses.

The `Error` oplog entries are not holding any information and can only be used to decide if there were N retries at the end of the oplog.

Some changes should be made:
- Enough information in the error entries to be able to create a `RecoveryDecision` just from oplog entries
- Maybe make retry count a cached value in `WorkerStatusRecord`
-

### PR DESCRIPTION
**Pull request by vigoo**
Resolves #289

### CODE REVIEW

File: golem-client/build.rs [hunk 1]
```diff
@@ -44,3 +46,20 @@ fn generate(yaml_path: PathBuf, out_dir: OsString) {
...
+        let b = std::fs::read(&dst)?;
+        if a != b {
+            std::fs::copy(src, dst)?;
+        }
+        Ok(())
+    } else {
+        std::fs::copy(src, dst)?;
+        Ok(())
+    }
+}
```
Comment (afsalthaj) [inline golem-client/build.rs:65]: 👍

File: golem-common/src/model/oplog.rs [hunk 2]
```diff
@@ -218,6 +227,22 @@ pub enum WrappedFunctionType {
     WriteRemote,
 }
 
+/// Describes the error that occurred in the worker
+#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize, Encode, Decode)]
+pub enum WorkerError {
+    Unknown(String),
+    StackOverflow,
```
Comment (afsalthaj) [inline golem-common/src/model/oplog.rs:234]: Interesting

File: golem-worker-executor-base/src/durable_host/mod.rs [hunk 3]
```diff
@@ -731,73 +733,66 @@ impl<Ctx: WorkerCtx> InvocationHooks for DurableWorkerCtx<Ctx> {
...
+                    true
+                }
+                TrapType::Exit => {
+                    self.set_oplog_entry(OplogEntry::Exited {
+                        timestamp: Timestamp::now_utc(),
+                    })
+                    .await;
+                    true
+                }
+                _ => false,
```
Comment (afsalthaj) [inline golem-worker-executor-base/src/durable_host/mod.rs:763]: So for rest of the types , we don't need to set the oplog entry

File: golem-common/src/model/oplog.rs (hunk 2 above)
Comment (vigoo) [reply golem-common/src/model/oplog.rs:234]: Currently we only distinguish stack overflow because that is never retried.
I expect this will be extended in the future, for example with http-specific errors for which we need custom retry policies, etc.

**Review by jdegoes — APPROVED** [review]
