### PR TITLE
Fixes related to capturing stderr with failures

### LINKED ISSUE #930: Last error should contain the related stdout / stderr
Invoke-and-await now shows the stack trace and related outputs, but later the output cannot be retrieved, it should be part of last error, so it is visible when using worker get.

### PR DESCRIPTION
**Pull request by vigoo**
Resolves #930

### CODE REVIEW

File: golem-test-framework/src/dsl/mod.rs [hunk 1]
```diff
@@ -82,15 +82,15 @@ pub trait TestDsl {
     async fn get_worker_metadata(
         &self,
         worker_id: &WorkerId,
-    ) -> crate::Result<Option<WorkerMetadata>>;
+    ) -> crate::Result<Option<(WorkerMetadata, Option<String>)>>;
```
Comment (noise64) [inline golem-test-framework/src/dsl/mod.rs:85]: can we create a struct for this tuple or make it part of the WorkerMetadata?

Comment (vigoo) [reply golem-test-framework/src/dsl/mod.rs:85]: It is intentionally not part of the worker metadata (because that's the actual serialized struct that is stored in redis, and the error information is gathered from oplog entries) .

I don't like using tuples anywhere in general, but in these tests, I felt that having 
``` let (metadata, _) = ...` where we don't care about the last failure is less annoying than completely changing the result type to something that wraps both. 

But I'm open to change my mind :)

**Review by noise64 — APPROVED** [review]
