### PR TITLE
Fix how invalid parameters are handled in worker executor

### LINKED ISSUE #1498: Worker revert does not revert to the correct index
Reproducing:

```
golem app new reproduce rust
cd reproduce
golem component new rust/example-todo-list test:todo
golem app build
golem app deploy
golem worker invoke test:todo/t1 count
golem worker invoke test:todo/t1 get '"x"'
golem worker invoke test:todo/t1 get '"x"'
golem worker invoke test:todo/t1 get '"x"'
curl --request POST \
  --url 'http://localhost:9881/v1/components/7686266d-5277-404c-8e14-a532955ab9d1/workers/t1/invoke-and-await?function=test%3Atodo-exports%2Ftest-todo-api.%7Bget%7D(id%3A%2Bstring)%2B-%3E%2Bresult%3Crecord%2B%7B%2Bid%3A%2Bstring%2C%2Btitle%3A%2Bstring%2C%2Bpriority%3A%2Benum%2B%7B%2Blow%2C%2Bmedium%2C%2Bhigh%2B%7D%2C%2Bstatus%3A%2Benum%2B%7B%2Bbacklog%2C%2Bin-progress%2C%2Bdone%2B%7D%2C%2Bcreated-timestamp%3A%2Bs64%2C%2Bupdated-timestamp%3A%2Bs64%2C%2Bdeadline%3A%2Boption%3Cs64%3E%2B%7D%2C%2Bstring%3E' \
  --header 'Content-Type: application/json' \
  --header 'User-Agent: insomnia/8.2.0' \
  --data '{"params":[{"typ":{"type":"Str"},"value":"x"},
					{"typ":{"type":"Str"},"value":"y"}]}'
golem worker list
golem worker oplog t1
```

at this point the worker is failed because of the forced invalid invocation via curl

```
golem worker revert t1 --number-of-invocations 1                                                                                                                                                                                     
golem worker oplog t1                             
```

This shows:

```
          result:            (err("Item with ID \'x\' not found!"))
#00016: INVOKE test:todo-exports/test-todo-api.{get}(id:+string)+->+result<record+{+id:+string,+title:+string,+priority:+enum+{+low,+medium,+high+},+status:+enum+{+backlog,+in-progress,+done+},+created-timestamp:+s64,+updated-timestamp:+s64,
     +deadline:+option<s64>+},+string>
          at:                2025-04-08T14:29:10.865Z
          idempotency key:   e1a004f6-df82-4065-a447-e85bbbde000a
          input:
            - "x"
#00017: ERROR
          at:                2025-04-08T14:29:10.871Z
          error:             Parameter type mismatch: expected 1, got 2 parameters
#00018: INVOKE test:todo-exports/test-todo-api.{get}(id:+string)+->+result<record+{+id:+string,+title:+string,+priority:+enum+{+low,+medium,+high+},+status:+enum+{+backlog,+in-progress,+done+},+created-timestamp:+s64,+updated-timestamp:+s64,
     +deadline:+option<s64>+},+string>
          at:                2025-04-08T14:29:11.028Z
          idempotency key:   e1a004f6-df82-4065-a447-e85bbbde000a
          input:
            - "x"
#00019: ERROR
          at:                2025-04-08T14:29:11.029Z
          error:             Parameter type mismatch: expected 1, got 2 parameters
#00020: ERROR
          at:                2025-04-08T14:29:11.181Z
          error:             Parameter type mismatch: expected 1, got 2 parameters
#00021: ERROR
          at:                2025-04-08T14:29:11.317Z
          error:             Parameter type mismatch: expected 1, got 2 parameters
#00022: ERROR
          at:                2025-04-08T14:29:11.687Z
          error:             Parameter type mismatch: expected 1, got 2 parameters
#00023: REVERT
          at:                2025-04-08T14:31:46.080Z
          to oplog index:    17
```

The target oplog index should be probably pointing go 16 because 
                                                                                                                                                                                   
```
golem worker invoke test:todo/t1 delete-done-items                                                                                                                                                                                  
```
fails with worker is already failed

and

```
golem worker get t1
```

says it is retrying

### PR DESCRIPTION
**Pull request by vigoo**
This makes it behaving the same as invalid function names - the worker remains usable after, and nothing is written to the oplog.

This also explains and fixes the revert related linked issue.

Resolves #1498

### CODE REVIEW

File: golem-test-framework/src/dsl/mod.rs [hunk 1]
```diff
@@ -1352,11 +1352,11 @@ impl<T: TestDependencies + Send + Sync> TestDsl for T {
     }
 
     async fn check_oplog_is_queryable(&self, worker_id: &WorkerId) -> crate::Result<()> {
-        let oplog = TestDsl::get_oplog(self, worker_id, OplogIndex::INITIAL).await?;
+        let _oplog = TestDsl::get_oplog(self, worker_id, OplogIndex::INITIAL).await?;
 
-        for (idx, entry) in oplog.iter().enumerate() {
-            debug!("#{}: {entry:#?}", idx + 1);
-        }
+        // for (idx, entry) in oplog.iter().enumerate() {
```
Comment (noise64) [inline golem-test-framework/src/dsl/mod.rs:1357]: did you kept these deliberately as comments? (or maybe use enabled tracing etc)

**Review by noise64 — APPROVED** [review]

File: golem-test-framework/src/dsl/mod.rs (hunk 1 above)
Comment (vigoo) [reply golem-test-framework/src/dsl/mod.rs:1357]: yes

Comment (vigoo) [reply golem-test-framework/src/dsl/mod.rs:1357]: i keep deleting it and having to rewrite every week
